config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/dashboard', to: 'pages#index'
    get '/user_allowances', to: 'user_allowances#index'
    get 'user_allowances/:month', to: 'user_allowances#list', as: :user_allowance_list
    get 'user_allowances/:month/user/:id', to: 'user_allowances#allowance', as: :user_allowance_allowance
    resources :licenses
    resources :users
    resources :projects
    get 'projects/:id/edit_member_license', to: 'projects#edit_member_license', as: :edit_member_license_project_path
    resources :projects do
      collection do
        get 'search'
      end
    end
  end
  get '*path', controller: 'application', action: 'render_404'
end

app/models/user_allowance.rb
class UserAllowance < ApplicationRecord
  belongs_to :user
  belongs_to :license

  def start_time
    self.date
  end
end

app/controllers/admin/user_allowances_controller.rb
class Admin::UserAllowancesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user
  require "csv"

  def index
    @monthly_allowance = UserAllowance.group("DATE_FORMAT(date, '%Y%m')").select("DATE_FORMAT(date, '%Y%m') as month")
  end
  def list
    @month = params[:month]
    @monthly_allowances = UserAllowance.where("DATE_FORMAT(date,'%Y%m') = #{@month}").joins(:user).group(:user_id).select(:name, :user_id)
    @monthly_allowances_first_date = UserAllowance.find_by("DATE_FORMAT(date,'%Y%m') = #{@month}").date 
  end
  def allowance
    @month = params[:month]
    @user_id = params[:id]
    @user = User.find(params[:id])
    @user_allowances = UserAllowance.where(user_id: @user).joins(:license).select(:date,:title,:license_id,:price)
    @monthly_allowances = UserAllowance.where("(DATE_FORMAT(date,'%Y%m') = #{@month}) AND (user_id = #{@user_id}) ").joins(:license).select(:title, :license_id)
    @monthly_allowances_sum = UserAllowance.where("(DATE_FORMAT(date, '%Y%m') = #{@month}) AND (user_id = #{@user_id})").joins(:license).group(:license_id).select("title, sum(price) as price, count(*) as count, license_id")
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_posts_csv(@monthly_allowances_sum)
      end
    end
  end

  private
  def admin_user
    redirect_to root_path unless current_user.is_admin == true
  end
  def send_posts_csv(sums)
    bom = "\uFEFF"
    csv_data = CSV.generate(bom) do |csv|
      csv_title = %W(#{@user.name}#{@month})
      csv << csv_title
      # トップ
      column_names = []
      column_names.push("手当名")
      # 1.upto(31) do |n|
      #   column_names.push("#{@month}/#{n}")
      # end
      column_names.push("回数","合計金額")
      csv << column_names
      # 手当カレンダー
      sums.each do |sum|
        column_values = []
        column_values.push(sum.title)
        # allowances = UserAllowance.where("(DATE_FORMAT(date,'%Y%m') = #{@month}) AND (user_id = #{@user_id}) ").joins(:license).select("count(*) as count")
        # 1.upto(31) do |n|
        #   if allowances.exists?("DATE_FORMAT(date, '%d') = #{n}")
        #     column_values.push(sum.price)
        #   else
        #     column_values.push("")
        #   end
        # end
        column_values.push(sum.count, sum.price)
        csv << column_values
      end
    end
    send_data(csv_data, filename: "#{@user.name}#{@month}手当.csv")
  end
end

app/helpers/admin/user_allowances_helper.rb
module Admin::UserAllowancesHelper
end

app/views/admin/user_allowances/allowance.html.erb
<div class="row mb-5">
  <div class="col-6">
    <h2 class="font-weight-bold"><%= @user.name %><br><%= @month %>手当一覧</h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "ユーザー一覧",admin_user_allowance_list_path(@month),class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<%= link_to "csvで出力する",admin_user_allowance_allowance_path(format: :csv) %>
<div class="table-responsive mb-3">
  <%= month_calendar events:@user_allowances do |date,allowances| %>
    <%= date %><br>
    <% allowances.each do |allowance| %>
      <%= allowance.title %> <%= allowance.price %>円<br>
    <% end %>
  <% end %>
</div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">手当名</th>
        <th scope="col">回数</th>
        <th scope="col">月合計</th>
      </tr>
    </thead>
    <tbody>
      <% @monthly_allowances_sum.each do |allowance| %>
        <tr>
          <td>
            <%= allowance.title %>
          </td>
          <td>
            <%= allowance.count %>
          </td>
          <td>
            <%= allowance.price %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/user_allowances/index.html.erb
<div class="row mb-5">
  <div class="col-12">
    <h2 class="font-weight-bold">手当月一覧</h2>
  </div>
</div>
<table>
  <tbody>
    <% @monthly_allowance.each do |allowance| %>
      <tr>
        <td>
          <%= link_to allowance.month, admin_user_allowance_list_path(allowance.month), class: "font-weight-bold" %>の給与
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/user_allowances/list.html.erb
<div class="row mb-5">
  <div class="col-6">
    <h2 class="font-weight-bold"><%= @month %>手当ユーザー一覧</h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "手当月一覧",admin_user_allowances_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<table class="table mt-5">
  <thead class="thead-light">
    <tr>
      <th scope="col">名前</th>
    </tr>
  </thead>
  <tbody>
    <% @monthly_allowances.each do |user| %>
      <tr>
        <td>
          <%= link_to user.user.name, admin_user_allowance_allowance_path(@month, user.user_id, start_date: @monthly_allowances_first_date), class: "font-weight-bold" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>