config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/dashboard', to: 'pages#index'
    get '/user_allowances', to: 'user_allowances#index'
    get 'user_allowances/:month', to: 'user_allowances#list', as: :user_allowance_list
    get 'user_allowances/:month/user/:id', to: 'user_allowances#allowance', as: :user_allowance_allowance
    resources :licenses
    resources :users
    resources :projects
    get 'projects/:id/edit_member_license', to: 'projects#edit_member_license', as: :edit_member_license_project_path
    resources :projects do
      collection do
        get 'search'
      end
    end
  end
  get '*path', controller: 'application', action: 'render_404'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :driver, optional: true
  belongs_to :leader, optional: true

  validates :name, presence: true
  validates :date, presence: true

  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  accepts_nested_attributes_for :project_users, allow_destroy: true
  validates_associated :users

  has_many :project_licenses, dependent: :destroy
  has_many :licenses, through: :project_licenses
  accepts_nested_attributes_for :project_licenses, allow_destroy: true
  validates_associated :licenses

  has_many :drivers, dependent: :destroy
  has_many :users, through: :drivers
  accepts_nested_attributes_for :drivers, allow_destroy: true
  validates_associated :users

  has_many :trips, dependent: :destroy
  has_many :users, through: :trips
  accepts_nested_attributes_for :trips, allow_destroy: true
  validates_associated :users

  has_many :user_allowance, dependent: :destroy
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :search
  before_action :authenticate_user!

  def search
    @q = Project.order(created_at: :desc).ransack(params[:q])
  end

  def index
    @project_results = @q.result(distinct: true)
    @projects = Project.page(params[:page]).per(10).order(created_at: :desc)
  end

  def new
    @project = Project.new
    @users = User.all
    @licenses = License.where.not(title: "隊長手当").where.not(title: "運転手当").where.not(title: "出張手当").where.not(title: "規制手当")
  end

  def create
    @project = Project.create(project_params)
    if @project.save
      flash[:success] = "伝票の作成に成功しました。"
      @leader_license = License.find_by(title: "隊長手当")
      UserAllowance.create(user_id: @project.leader_id, license_id: @leader_license.id, project_id: @project.id, date: @project.date, price: @leader_license.fee)
      @driver_license = License.find_by(title: "運転手当")
      @project.drivers.each do |driver| 
        UserAllowance.create!(user_id: driver.user_id, license_id: @driver_license.id, project_id: @project.id, date: @project.date, price: @driver_license.fee)
      end
      @trip_license = License.find_by(title: "出張手当")
      @project.trips.each do |trip| 
        UserAllowance.create!(user_id: trip.user_id, license_id: @trip_license.id, project_id: @project.id, date: @project.date, price: @trip_license.fee)
      end
      if @project.is_registration == true
        @registration_license = License.find_by(title: "規制手当")
        @project.project_users.each do |user|
          UserAllowance.create!(user_id: user.user_id, license_id: @registration_license.id, project_id: @project.id, date: @project.date, price: @registration_license.fee)
        end
      end
      # その他資格保存
      @licenses = @project.project_licenses
      @members = @project.project_users
      @licenses.each do |license|
        @members.each do |member|
          @member_licenses = member.user.license_users
          @member_licenses.each do |m|
            if m.license_id == license.license_id
              UserAllowance.create!(user_id: member.user_id, license_id: license.license_id, project_id: @project.id, date: @project.date, price: license.license.fee)
            end
          end
        end
      end
      redirect_to admin_edit_member_license_project_path_path(@project.id)
    else
      render "new"
    end
  end

  def edit_member_license
    @project = Project.find(params[:id])
    @users = User.all
    @members = ProjectUser.where(project: params[:id])
  end

  def edit
    @project = Project.find(params[:id])
    @users = User.all
    @members = ProjectUser.where(project: params[:id])
    @licenses = License.where.not(title: "隊長手当").where.not(title: "運転手当").where.not(title: "出張手当").where.not(title: "規制手当")
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:success] = "伝票の編集に成功しました。"
      @leader_license = License.find_by(title: "隊長手当")
      leader_allowance = UserAllowance.find_or_initialize_by(license_id: @leader_license.id, project_id: @project.id)
      if leader_allowance.new_record?
        UserAllowance.create(user_id: @project.leader_id, license_id: @leader_license.id, project_id: @project.id, date: @project.date, price: @leader_license.fee)
      else
        leader_allowance.update(user_id: @project.leader_id)
      end

      @driver_license = License.find_by(title: "運転手当")
      #1ドライバ―のユーザーidを取得
      drivers = Driver.where(project_id: @project.id)
      #2UserAllowanceにふくまれるuser_idを取得
      original_user_allowances = UserAllowance.where(license_id: @driver_license.id, project_id: @project.id)
      #3ドライバ―に含まれてuserAllowanceに含まれないものを追加する
      drivers.each do |driver|
        if original_user_allowances.find_by(user_id: driver.user_id) == nil
          UserAllowance.create(user_id: driver.user_id, license_id: @driver_license.id, project_id: @project.id, date: @project.date, price: @driver_license.fee)
        end
      end
      #4UserAllowanceに含まれてドライバ―に含まれないものを追加する
      original_user_allowances.each do |original_user_allowance|
        if drivers.find_by(user_id: original_user_allowance.user_id) == nil
          original_user_allowance.destroy
        end
      end

      @trip_license = License.find_by(title: "出張手当")
      #1出張のユーザーidを取得
      trips = Trip.where(project_id: @project.id)
      #2UserAllowanceにふくまれるuser_idを取得
      original_user_allowances = UserAllowance.where(license_id: @trip_license.id, project_id: @project.id)
      #3出張に含まれてuserAllowanceに含まれないものを追加する
      trips.each do |trip|
        if original_user_allowances.find_by(user_id: trip.user_id) == nil
          UserAllowance.create(user_id: trip.user_id, license_id: @trip_license.id, project_id: @project.id, date: @project.date, price: @trip_license.fee)
        end
      end
      #4UserAllowanceに含まれて出張に含まれないものを追加する
      original_user_allowances.each do |original_user_allowance|
        if trips.find_by(user_id: original_user_allowance.user_id) == nil
          original_user_allowance.destroy
        end
      end

      @registration_license = License.find_by(title: "規制手当")
      registration_licenses = UserAllowance.where(license_id: @registration_license.id, project_id: @project.id)

      if registration_licenses.count > 0
        # 規制がtrueからfalseに変更した時　できた
        if @project.is_registration == false
          registration_licenses.destroy_all
        end
      else
        # 規制がfalseからtrueに変更した時 出来てない
        if @project.is_registration == true
          @project.project_users.each do |user|
            UserAllowance.create!(user_id: user.user_id, license_id: @registration_license.id, project_id: @project.id, date: @project.date, price: @registration_license.fee)
          end
        end
      end
      # その他資格保存
      @licenses = @project.project_licenses
      @members = @project.project_users
      @licenses.each do |license|
        @members.each do |member|
          @member_licenses = member.user.license_users
          @member_licenses.each do |m|
            if m.license_id == license.license_id
              UserAllowance.create!(user_id: member.user_id, license_id: license.license_id, project_id: @project.id, date: @project.date, price: license.license.fee)
            end
          end
        end
      end
      redirect_to admin_projects_path
    else
      render "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:success] = "伝票の削除に成功しました。"
      redirect_to admin_projects_path
    else
      render "edit"
      flash[:danger] = "伝票の削除に失敗しました。"
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :date, :start_time, :end_time, :leader_id, :is_registration, :address, :supplement, :is_read,
       project_users_attributes: [:id,:project_id, :user_id, :_destroy],
       project_licenses_attributes: [:id,:project_id, :license_id, :_destroy],
       drivers_attributes: [:id,:project_id, :user_id, :_destroy],
       trips_attributes: [:id,:project_id, :user_id, :_destroy]
      )
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/views/admin/projects/_driver_fields.html.erb
<div class="nested-fields mb-3 row">
  <div class="col-8">
    <%= f.select :user_id, @members.map{|member| [member.user.name, member.user_id]}, {prompt: "運転手を選択してください"}, {class: 'form-control'} %>
  </div>
  <div class="col-4">
    <%= link_to_remove_association f do %>
      <div class="btn btn-outline-secondary">削除</div>
    <% end %>
  </div>
</div>

app/views/admin/projects/_form.html.erb
<%= form_with(model:@project, url:admin_projects_path, method: :post, local:true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <div class="card-body">
    <div class="form-group">
      <%= f.label :name, "業者名" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :date, "日付" %>
      <%= f.date_field :date, class:"form-control" %>
    </div>
    <div class="form-group" id='detail-association-insertion-point'>
      <%= f.label :project_users, "メンバー" %>
      <%= f.fields_for :project_users do |project_user| %>
        <%= render 'project_user_fields', f: project_user %>
      <% end %>
      <div class="add-association">
        <%= link_to_add_association f, :project_users, class: "btn btn-outline-dark" do %>
          追加
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= f.label :start_time, "開始時間" %>
          <%= f.time_field :start_time, class:"form-control" %>
        </div>
      </div>
      <div class="col">
        <div class="form-group">
          <%= f.label :end_time, "終了時間" %>
          <%= f.time_field :end_time, class:"form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group form-check">
      <%= f.check_box :is_registration, class:"form-check-input" %>
      <%= f.label :is_registration, "規制", class:"form-check-label" %>
    </div>
    <div class="form-group" id='detail-association-insertion-point'>
      <%= f.label :project_licenses, "資格" %>
      <%= f.fields_for :project_licenses do |project_license| %>
        <%= render 'project_license_fields', f: project_license %>
      <% end %>
      <div class="add-association">
        <%= link_to_add_association f, :project_licenses, class: "btn btn-outline-dark" do %>
          追加
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :address, "場所" %>
      <%= f.text_field :address, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :supplement, "備考" %>
      <%= f.text_area :supplement, class:"form-control" %>
    </div>
  </div>
  <div class="card-footer text-right">
    <%= f.submit "登録",class:"btn btn-primary" %>
  </div>
<%end%>

app/views/admin/projects/_project_license_fields.html.erb
<div class="nested-fields mb-3 row">
  <div class="col-8">
    <%= f.collection_select :license_id, License.where.not(title: "隊長手当").where.not(title: "運転手当").where.not(title: "出張手当").where.not(title: "規制手当"), :id, :title, {prompt: "資格を選択してください"}, {class: 'form-control'} %>
  </div>
  <div class="col-4">
    <%= link_to_remove_association f do %>
      <div class="btn btn-outline-secondary">削除</div>
    <% end %>
  </div>
</div>

app/views/admin/projects/_project_user_fields.html.erb
<div class="nested-fields mb-3 row">
  <div class="col-8">
    <%= f.collection_select :user_id, User.all, :id, :name, {prompt: "メンバーを選択してください"}, {class: 'form-control'} %>
  </div>
  <div class="col-4">
    <%= link_to_remove_association f do %>
      <div class="btn btn-outline-secondary">削除</div>
    <% end %>
  </div>
</div>

app/views/admin/projects/_trip_fields.html.erb
<div class="nested-fields mb-3 row">
  <div class="col-8">
    <%= f.select :user_id, @members.map{|member| [member.user.name, member.user_id]}, {prompt: "出張者を選択してください"}, {class: 'form-control'} %>
  </div>
  <div class="col-4">
    <%= link_to_remove_association f do %>
      <div class="btn btn-outline-secondary">削除</div>
    <% end %>
  </div>
</div>

app/views/admin/projects/edit.html.erb
<div class="row mb-5">
  <div class="col-6 font-weight-bold">
    <h2>伝票編集</h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "一覧に戻る",admin_projects_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<%= render "shared/flash_message" %>
<div class="card">
  <div class="card-header">
    伝票更新
  </div>
  <%= form_for(@project, url:{controller:'projects', action: 'update',id:@project.id}) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="card-body">
      <div class="form-group">
        <%= f.label :name, "業者名" %>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :date, "日付" %>
        <%= f.date_field :date, class:"form-control" %>
      </div>
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.fields_for :project_users do |project_user| %>
          <%= render 'project_user_fields', f: project_user %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :project_users, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="form-group">
            <%= f.label :start_time, "開始時間" %>
            <%= f.time_field :start_time, class:"form-control" %>
          </div>
        </div>
        <div class="col">
          <div class="form-group">
            <%= f.label :end_time, "終了時間" %>
            <%= f.time_field :end_time, class:"form-control" %>
          </div>
        </div>
      </div>
      <div class="form-group form-check">
        <%= f.check_box :is_registration, class:"form-check-input" %>
        <%= f.label :is_registration, "規制", class:"form-check-label" %>
      </div>
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :drivers, "運転" %>
        <%= f.fields_for :drivers do |driver| %>
          <%= render 'driver_fields', f: driver %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :drivers, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :trips, "出張" %>
        <%= f.fields_for :trips do |trip| %>
          <%= render 'trip_fields', f: trip %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :trips, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :leader_id, "隊長" %>
        <%= f.select :leader_id, @members.map{|member| [member.user.name, member.user_id]}, {prompt: "隊長を選択してください"}, {class: 'form-control'} %>
      </div>
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :project_licenses, "資格" %>
        <%= f.fields_for :project_licenses do |project_license| %>
          <%= render 'project_license_fields', f: project_license %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :project_licenses, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :address, "場所" %>
        <%= f.text_field :address, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :supplement, "備考" %>
        <%= f.text_area :supplement, class:"form-control" %>
      </div>
      <% if admin? %>
        <div class="form-group form-check">
          <%= f.check_box :is_read, class:"form-check-input" %>
          <%= f.label :is_read, "既読", class:"form-check-label" %>
        </div>
      <% end %>
    </div>
    <div class="card-footer text-right">
      <%= link_to "削除", "/admin/projects/#{@project.id}", class:"btn btn-danger", method: :delete %>
      <%= f.submit "登録",class:"btn btn-primary" %>
    </div>
  <%end%>
</div>

app/views/admin/projects/edit_member.html.erb
<div class="row mb-5">
  <div class="col-6 font-weight-bold">
    <h2></h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "一覧に戻る",admin_projects_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<%= render "shared/flash_message" %>
<div class="card">
  <div class="card-header">
    資格更新
  </div>
  <%= form_for(@project, url:{controller:'projects', action: 'update',id:@project.id}) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="card-body">
      <div class="form-group">
        <%= f.label :leader_id, "隊長" %>
        <%= f.select :leader_id, @members.map{|member| [member.user.name, member.user_id]}, {prompt: "隊長を選択してください"}, {class: 'form-control'} %>
      </div>  
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :drivers, "運転" %>
        <%= f.fields_for :drivers do |driver| %>
          <%= render 'driver_fields', f: driver %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :drivers, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :trips, "出張" %>
        <%= f.fields_for :trips do |trip| %>
          <%= render 'trip_fields', f: trip %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :trips, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>    
    </div>
    <div class="card-footer text-right">
      <%= link_to "削除", "/admin/projects/#{@project.id}", class:"btn btn-danger", method: :delete %>
      <%= f.submit "登録",class:"btn btn-primary" %>
    </div>
  <%end%>
</div>

app/views/admin/projects/edit_member_license.html.erb
<div class="row mb-5">
  <div class="col-6 font-weight-bold">
    <h2></h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "一覧に戻る",admin_projects_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<%= render "shared/flash_message" %>
<div class="card">
  <div class="card-header">
    資格更新
  </div>
  <%= form_for(@project, url:{controller:'projects', action: 'update',id:@project.id}) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="card-body">
      <div class="form-group">
        <%= f.label :leader_id, "隊長" %>
        <%= f.select :leader_id, @members.map{|member| [member.user.name, member.user_id]}, {prompt: "隊長を選択してください"}, {class: 'form-control'} %>
      </div>  
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :drivers, "運転" %>
        <%= f.fields_for :drivers do |driver| %>
          <%= render 'driver_fields', f: driver %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :drivers, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :trips, "出張" %>
        <%= f.fields_for :trips do |trip| %>
          <%= render 'trip_fields', f: trip %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :trips, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>    
    </div>
    <div class="card-footer text-right">
      <%= link_to "削除", "/admin/projects/#{@project.id}", class:"btn btn-danger", method: :delete %>
      <%= f.submit "登録",class:"btn btn-primary" %>
    </div>
  <%end%>
</div>

app/views/admin/projects/index.html.erb
<div class="row mb-5">
  <div class="col-6">
    <h2 class="font-weight-bold">伝票一覧</h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "新規追加",new_admin_project_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<div class="card mb-4">
  <div class="card-header">
    伝票検索
  </div>
  <div class="card-body">
    <%= search_form_for(@q, url:admin_projects_path) do |f| %>
      <div class="row">
        <div class="col-12">
          <div class="form-group">
            <%= f.label :name_eq, "業者名" %>
            <%= f.text_field :name_eq, class:"form-control" %>
          </div>
        </div>
        <div class="col-12">
          <div class="form-group row">
            <div class="col-6">
              <%= f.date_field :date_gteq, class:"form-control" %>
            </div>
            <div class="col-6">
              <%= f.date_field :date_lteq, class:"form-control" %>
            </div>
          </div>
        </div>
      </div>
      <%= f.submit "検索", class:"btn btn-warning font-weight-bold" %>
    <% end %>
  </div>
</div>
<%= render "shared/flash_message" %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">日付</th>
      <th scope="col">業者名</th>
      <th scope="col">編集</th>
    </tr>
  </thead>
  <tbody>
    <% if @project_results.present? %>
      <% @project_results.each do |project| %>
        <% if admin? or project.is_read == nil %>
          <tr>
            <td><%= project.date %></td>
            <td><%= project.name %></td>
            <td><%= link_to "編集",edit_admin_project_path(project),class:"btn btn-warning font-weight-bold" %></td>
          </tr>
        <% end %>
      <% end %>
    <% else %>
      <% @projects.each do |project| %>
        <% if admin? or project.is_read == nil %>
          <tr>
            <td><%= project.date %></td>
            <td><%= project.name %></td>
            <td><%= link_to "編集",edit_admin_project_path(project),class:"btn btn-warning font-weight-bold" %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= paginate @projects %>

app/views/admin/projects/new.html.erb
<div class="row mb-5">
  <div class="col-6 font-weight-bold">
    <h2>伝票追加</h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "一覧に戻る",admin_projects_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>

<div class="card mb-5">
  <div class="card-header">
    伝票追加
  </div>
  <%= render "form" %>
</div>

app/views/admin/projects/post.html.erb
<div class="row mb-5">
  <div class="col-6 font-weight-bold">
    <h2></h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "一覧に戻る",admin_projects_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<%= render "shared/flash_message" %>
<div class="card">
  <div class="card-header">
    資格更新
  </div>
  <%= form_for(@project, url:{controller:'projects', action: 'update',id:@project.id}) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="card-body">
      <div class="form-group">
        <%= f.label :leader_id, "隊長" %>
        <%= f.select :leader_id, @members.map{|member| [member.user.name, member.user_id]}, {prompt: "隊長を選択してください"}, {class: 'form-control'} %>
      </div>  
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :drivers, "運転" %>
        <%= f.fields_for :drivers do |driver| %>
          <%= render 'driver_fields', f: driver %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :drivers, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.label :trips, "出張" %>
        <%= f.fields_for :trips do |trip| %>
          <%= render 'trip_fields', f: trip %>
        <% end %>
        <div class="add-association">
          <%= link_to_add_association f, :trips, class: "btn btn-outline-dark" do %>
            追加
          <% end %>
        </div>
      </div>    
    </div>
    <div class="card-footer text-right">
      <%= link_to "削除", "/admin/projects/#{@project.id}", class:"btn btn-danger", method: :delete %>
      <%= f.submit "登録",class:"btn btn-primary" %>
    </div>
  <%end%>
</div>