config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/dashboard', to: 'pages#index'
    get '/user_allowances', to: 'user_allowances#index'
    get 'user_allowances/:month', to: 'user_allowances#list', as: :user_allowance_list
    get 'user_allowances/:month/user/:id', to: 'user_allowances#allowance', as: :user_allowance_allowance
    resources :licenses
    resources :users
    resources :projects
    get 'projects/:id/edit_member_license', to: 'projects#edit_member_license', as: :edit_member_license_project_path
    resources :projects do
      collection do
        get 'search'
      end
    end
  end
  get '*path', controller: 'application', action: 'render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/license.rb
class License < ApplicationRecord
  validates :title, presence: true
  validates :fee, presence: true
  has_many :license_users
  has_many :users, through: :license_users
  has_many :project_licenses
  has_many :projects, through: :project_licenses
end

app/models/license_user.rb
class LicenseUser < ApplicationRecord
  belongs_to :license
  belongs_to :user
  validates :license_id, uniqueness: { scope: :user_id }
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :driver, optional: true
  belongs_to :leader, optional: true

  validates :name, presence: true
  validates :date, presence: true

  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  accepts_nested_attributes_for :project_users, allow_destroy: true
  validates_associated :users

  has_many :project_licenses, dependent: :destroy
  has_many :licenses, through: :project_licenses
  accepts_nested_attributes_for :project_licenses, allow_destroy: true
  validates_associated :licenses

  has_many :drivers, dependent: :destroy
  has_many :users, through: :drivers
  accepts_nested_attributes_for :drivers, allow_destroy: true
  validates_associated :users

  has_many :trips, dependent: :destroy
  has_many :users, through: :trips
  accepts_nested_attributes_for :trips, allow_destroy: true
  validates_associated :users

  has_many :user_allowance, dependent: :destroy
end

app/models/project_license.rb
class ProjectLicense < ApplicationRecord
  belongs_to :project
  belongs_to :license
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates :project, uniqueness: { scope: :user }
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :license_users, dependent: :destroy
  has_many :licenses, through: :license_users
  accepts_nested_attributes_for :license_users, allow_destroy: true
  validates_associated :licenses
  # validationを修正
  has_many :project_users
  has_many :projects, through: :project_users

  has_many :drivers
  has_many :projects, through: :drivers

  has_many :trips
  has_many :projects, through: :trips
end

app/models/user_allowance.rb
class UserAllowance < ApplicationRecord
  belongs_to :user
  belongs_to :license

  def start_time
    self.date
  end
end

app/controllers/admin/licenses_controller.rb
class Admin::LicensesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user

  def index
    @licenses = License.page(params[:page]).per(10).order(created_at: :desc)
  end

  def new
    @license = License.new
  end

  def create
    @license = License.create(license_params)
    if @license.save
      flash[:success] = "資格の作成に成功しました。"
      redirect_to admin_licenses_path
    else
      render "new"
    end
  end

  def edit
    @license = License.find(params[:id])
  end

  def update
    @license = License.find(params[:id])
    if @license.update(license_params)
      flash[:success] = "資格の編集に成功しました。"
      redirect_to admin_licenses_path
    else
      render "edit"
    end
  end

  def destroy
    @license=License.find(params[:id])
    begin
      @license.destroy
      flash[:success] = "資格の削除に成功しました。"
      redirect_to admin_licenses_path
    rescue
      render "edit"
      flash[:danger] = "資格の削除に失敗しました。"
    end
  end

  private
  def license_params
    params.require(:license).permit(:title, :fee)
  end

  def admin_user
    redirect_to root_path unless current_user.is_admin == true
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user

  def index
  end
  
  private
  def admin_user
    redirect_to root_path unless current_user.is_admin == true
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, except: :show

  def index
    @users = User.page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  # 同じ値が入らないようにする
  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = "社員の作成に成功しました。"
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "社員の編集に成功しました。"
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    begin
      @user.destroy
      flash[:success] = "社員の削除に成功しました。"
      redirect_to admin_users_path
    rescue
      render "edit"
      flash[:danger] = "社員の削除に失敗しました。"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :is_admin, license_users_attributes: [:id, :license_id, :user_id, :_destroy])
  end

  def admin_user
    redirect_to root_path unless current_user.is_admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500

  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end

  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/licenses_helper.rb
module Admin::LicensesHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def admin?
    current_user.is_admin == true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/licenses/_form.html.erb
<%= form_with(model:@license, url:admin_licenses_path, method: :post, local:true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>
<div class="card-body">
  <div class="form-group">
    <%= f.label :title, "資格名" %>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :fee, "金額"%>
    <%= f.number_field :fee, class:"form-control" %>
  </div>
  </div>
  <div class="card-footer text-right">
    <%= f.submit "登録",class:"btn btn-primary" %>
  </div>
<%end%>

app/views/admin/licenses/edit.html.erb
<div class="row mb-5">
  <div class="col-6 font-weight-bold">
    <h2>資格編集</h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "一覧に戻る",admin_licenses_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<%= render "shared/flash_message" %>
<div class="card">
  <div class="card-header">
    資格更新
  </div>
  <%= form_for(@license, url:{controller:'licenses', action: 'update',id:@license.id}) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="card-body">
      <div class="form-group">
        <%= f.label :title, "資格名" %>
        <%= f.text_field :title, class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :fee, "金額"%>
        <%= f.number_field :fee, class:"form-control" %>
      </div>
    </div>
    <div class="card-footer text-right">
      <%= link_to "削除", "/admin/licenses/#{@license.id}", class:"btn btn-danger", method: :delete %>
      <%= f.submit "登録",class:"btn btn-primary" %>
    </div>
  <%end%>
</div>

app/views/admin/licenses/index.html.erb
<div class="row mb-5">
  <div class="col-6">
    <h2 class="font-weight-bold">資格一覧</h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "新規追加",new_admin_license_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>
<%= render "shared/flash_message" %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">資格名</th>
      <th scope="col">手当</th>
      <th scope="col">編集</th>
    </tr>
  </thead>
  <tbody>
    <% @licenses.each do |license| %>
      <tr>
        <td><%= license.title %></td>
        <td><%= license.fee %></td>
        <td><%= link_to "編集",edit_admin_license_path(license),class:"btn btn-warning font-weight-bold" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @licenses %>

app/views/admin/licenses/new.html.erb
<div class="row mb-5">
  <div class="col-6 font-weight-bold">
    <h2>資格追加</h2>
  </div>
  <div class="col-6 text-right">
    <%= link_to "一覧に戻る",admin_licenses_path,class:"btn btn-warning font-weight-bold" %>
  </div>
</div>

<div class="card">
  <div class="card-header">
    資格追加
  </div>
  <%= render "form" %>
</div>